M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu18.04.1} date Thu Apr 21 22:13:43 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-21T22:13:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X6.5394Y-2.5057
X6.5394Y-2.7813
T0
M30
